spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: xpzheng
    password: 123456
  mvc:
     dispatch-options-request: true
mybatis:
  type-aliases-package: com.xpzheng.blog.model
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
debug: true
server:
  port: 8888
  servlet:
      context-path: /api
logging:
  level:
    root: INFO
    com:
      xpzheng: INFO